# Base docker-compose config for single application
# included by separate dcape app if USE_DCAPE_DC=yes

version: '3'

services:
  app:
    image: ${IMAGE}:${IMAGE_VER}
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.${APP_TAG}.rule=Host(`${APP_SITE:?Must be set}`)
      - traefik.http.routers.${APP_TAG}.tls=${USE_TLS}
      - traefik.http.routers.${APP_TAG}.tls.certresolver=default
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  default:
    name: ${DCAPE_NET}
    external: true
