# dcape Makefile
SHELL             = /bin/bash
CFG               = .env
CFG_BAK          ?= $(CFG).bak
DCAPE_USED        = 1

TZ               ?= $(shell cat /etc/timezone)
DCINC             = docker-compose.inc.yml

# check this files for update docker-compose.yml
DCFILES           = $(shell find apps/ -name $(DCINC) -print | sort)

PROJECT_NAME     ?= dcape
DOMAIN           ?= dev.lan
APPS_SYS         ?= db
APPS             ?= traefik portainer enfist cis

# Postgresql Database image
PG_IMAGE         ?= postgres:12.1-alpine
# Postgresql Database superuser password
PG_DB_PASS       ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 2>/dev/null | head -c14; echo)
# Postgresql Database encoding
PG_ENCODING      ?= en_US.UTF-8
# port on localhost postgresql listen on
PG_PORT_LOCAL    ?= 5433
# Dump name suffix to load on db-create
PG_SOURCE_SUFFIX ?=

# Docker-compose image tag
DC_VER           ?= 1.23.2

# Config store url
ENFIST_URL       ?= http://enfist:8080/rpc

# ------------------------------------------------------------------------------

define CONFIG_DEF
# dcape config file, generated by make $(CFG)

# General settings

# containers name prefix
PROJECT_NAME=$(PROJECT_NAME)

# Default domain
DOMAIN=$(DOMAIN)

# App list, for use in make only
APPS="$(shell echo $(APPS))"

# create db cluster with this timezone
# (also used by gitea container)
TZ=$(TZ)

# Postgresql Database image
PG_IMAGE=$(PG_IMAGE)
# Postgresql Database superuser password
PG_DB_PASS=$(PG_DB_PASS)
# Postgresql Database encoding
PG_ENCODING=$(PG_ENCODING)
# port on localhost postgresql listen on
PG_PORT_LOCAL=$(PG_PORT_LOCAL)

endef
export CONFIG_DEF

# ------------------------------------------------------------------------------

# if exists - load old values
-include $(CFG_BAK)
export

-include $(CFG)
export

.PHONY: deps init-master init-slave init-local init apply up reup down dc db-create db-drop env-get env-set help

# ------------------------------------------------------------------------------

all: help

include apps/*/Makefile

## установка зависимостей
deps:
	@echo "*** $@ ***"
	@sudo apt-get update && sudo apt-get install -y \
	  gawk wget curl apache2-utils openssh-client

## Init internet server with gitea and personal letsencrypt cert for all apps (redirect http to https)
init-master-prod: APPS = traefik-acme gitea portainer enfist cis
init-master-prod: init

## Init internet server without gitea and personal letsencrypt cert for all apps (redirect http to https)
init-slave-prod: APPS = traefik-acme portainer enfist cis
init-slave-prod: init

## Init internet server with gitea and ssl for build-in apps (redirect http to https)
init-master-dev: APPS = traefik-acme-dev gitea portainer enfist cis
init-master-dev: init

## Init internet server without gitea and ssl for built-in apps (redirect http to https)
init-slave-dev: APPS = traefik-acme-dev portainer enfist cis
init-slave-dev: init

## Init internet server with gitea and one woldcards cert for all apps (redirect http to https)
init-master-wild: APPS = traefik-acme-wild gitea portainer enfist cis
init-master-wild: init

## Init internet server without gitea and one wildcards cert for all apps (redirect http to https)
init-slave-wild: APPS = traefik-acme-wild portainer enfist cis
init-slave-wild: init

## Init local server
init-local: APPS = traefik gitea portainer enfist cis
init-local: init

## Initially create .enc file with defaults
init:
	@echo "*** $@ $(APPS) ***"
	@[ -d var/data ] || mkdir -p var/data
	@[ -f .env ] && { echo ".env already exists. Skipping" ; exit 1 ; } || true
	@echo "$$CONFIG_DEF" > .env
	@for f in $(shell echo $(APPS)) ; do echo $$f ; $(MAKE) -s $${f}-init ; done

## Apply config to app files & db
apply:
	@echo "*** $@ $(APPS) ***"
	@$(MAKE) -s dc CMD="up -d $(APPS_SYS)" || echo ""
	@for f in $(shell echo $(APPS)) ; do $(MAKE) -s $${f}-apply ; done

# build file from app templates
docker-compose.yml: $(DCINC) $(DCFILES)
	@echo "*** $@ ***"
	@echo "# WARNING! This file was generated by make. DO NOT EDIT" > $@
	@cat $(DCINC) >> $@
	@for f in $(shell echo $(APPS)) ; do cat apps/$$f/$(DCINC) >> $@ ; done

## старт контейнеров
up:
up: CMD=up -d $(APPS_SYS) $(shell echo $(APPS))
up: dc

## рестарт контейнеров
reup:
reup: CMD=up --force-recreate -d $(APPS_SYS) $(shell echo $(APPS))
reup: dc

## остановка и удаление всех контейнеров
down:
down: CMD=down
down: dc

## separate start of traefik in the interactive mode, is used for get wild cert
## for manual provider and DNS challenge (not use vars for manual provider)
wild: 
wild: CMD=run --rm traefik-acme-wild
wild: dc


# ------------------------------------------------------------------------------
# Upgrade postgres databases via pipeline (pg_dumpall | psql), bacause using pg_dump 
# we get error if the cluster has databases with different encodings
# for upgrade: 1. set PG_IMAGE on new postgres container:version;
# 2. make pg_upgrade_wpipe; 3. its all - check new pg, if Ok remove dir: ./var/data/<db_previous_version>
pg_upgrade_wpipe:
	@echo "*** $@ *** " ; \
	  DCAPE_DB=$${PROJECT_NAME}_db_1 ; \
	  DCAPE_DB_NEW="dcape_db_new" ; \
	  PG_PORT_NEW=$(shell expr $(PG_PORT_LOCAL) + 1) ; \
	  PG_NEW_MAJOR_VER=`docker inspect --type=image $$PG_IMAGE | jq -r '.[0].ContainerConfig.Env[] | capture("PG_MAJOR=(?<a>.+)") | .a'`  ; \
	  PG_USE_MAJOR_VER=`docker inspect $$DCAPE_DB | jq -r '.[0].Config.Env[] | capture("PG_MAJOR=(?<a>[0-9]+)") | .a'` ; \
	  echo "Prepare to upgrade the Postgres container PG_VER_USE=$$PG_USE_MAJOR_VER  ->  PG_VER_NEW=$$PG_NEW_MAJOR_VER" ; \
	  if [[ $$PG_USE_MAJOR_VER == $$PG_NEW_MAJOR_VER ]] ; then \
	    echo "Error, the PG_IMAGE variable contains the same version that is already use. To upgrade you need to set the new version in the PG_IMAGE variable." && \
	    exit 1 ; \
	  fi ; \
	  docker pull $$PG_IMAGE ; \
	  echo "Preparing the container with the new postgres version" ; \
	  echo "Deny connections from hosts" ; \
	  sed -i 's/host all all all md5/#host all all all md5/' $$PWD/var/data/db/pg_hba.conf ; \
	  echo "Start container with new Postgres..." ; \
	  docker run --rm -d \
	    --name $$DCAPE_DB_NEW \
	    -v $$PWD/var/data/db_$$PG_NEW_MAJOR_VER:/var/lib/postgresql/data \
	    -e "TZ=$$TZ" \
	    -e "LANG=$$PG_ENCODING" \
	    -e "POSTGRES_HOST_AUTH_METHOD=trust" \
	    --network=$$PROJECT_NAME"_default" \
	    -p "$$PG_PORT_NEW:5432" \
	    $$PG_IMAGE ; \
	  echo -n "Checking for new version Postgres is ready..."  ; \
	  retries=5 ;\
	  until docker exec -i -u postgres $$DCAPE_DB_NEW /bin/bash -c "psql -c '\l'" > /dev/null 2>&1 || [ $$retries -eq 0 ]; do sleep 1; ((retries--)); echo -n "."; done ; \
	  if [ $$retries -eq 0 ]; then \
	    echo "Error." ;\
	    echo "Something went wrong. PG not ready intil 5 seconds." ;\
	    exit 1 ;\
	  else \
	    echo "Ok." ; \
	  fi ;\
	  echo "Start database migration to a new Postgres." ;\
	  docker exec -i -u postgres $$DCAPE_DB_NEW /bin/bash -c "pg_dumpall -h db -p 5432 | psql -a " || exit 1 ;\
	  echo "Stopping PG_$$PG_USE_MAJOR_VER and PG_$$PG_NEW_MAJOR_VER Postgres container for reconfigure" ; \
	  docker stop $$DCAPE_DB_NEW $$DCAPE_DB || exit 1 ; \
	  echo "Create reserv copy with PG_USE datadir (move to db_$$PG_USE_MAJOR_VER dir)" ; \
	  WDIR="./var/data/" ; \
	  mv $$WDIR/db $$WDIR/db_$$PG_USE_MAJOR_VER ; \
	  echo "Change using postgresql datadir to PG_NEW" ; \
	  mv $$WDIR/db_$$PG_NEW_MAJOR_VER $$WDIR/db ; \
	  echo "Disable default configs file from PG_NEW (move postgres.conf and pg_hba.conf to files with .c2f extension)" ; \
	  mv $$WDIR/db/postgresql.conf $$WDIR/db/postgresql_default.c2f ; \
	  mv $$WDIR/db/pg_hba.conf $$WDIR/pg_hba_default.c2f ; \
	  echo "Copy config files from PG_USE version (postgresql.conf and pg_hba.conf)" ; \
	  cp $$WDIR/db_$$PG_USE_MAJOR_VER/postgresql.conf $$WDIR/db ; \
	  cp $$WDIR/db_$$PG_USE_MAJOR_VER/pg_hba.conf $$WDIR/db ;\
	  echo "The upgrade is complete, config file (postgresql.conf, pg_hba.conf) moved from old to new version." ; \
	  echo "Postgres is down, but ready for start. For start Postgres use command: make dc CMD=\"up -d db\"" ; \
	  echo "For more info see https://github.com/dopos/dcape/blob/master/POSTGRES.md"


# Upgrade postgres major version with pg_dumpall-psql
# Create dump for claster Postgres
pg_dumpall:
	@echo "Start $@ to pg_dumpall_$${PROJECT_NAME}_`date +"%d.%m.%Y"`.sql.gz" ;\
	  DCAPE_DB=$${PROJECT_NAME}_db_1 ; \
	  docker exec -u postgres $$DCAPE_DB pg_dumpall | gzip -7 -c > \
		./var/data/db-backup/pg_dumpall_$${PROJECT_NAME}_`date +"%d.%m.%Y"`.sql.gz

# Load dump for claster Postgres
pg_load_dumpall:
	@echo "Start $@ ..." ; \
	  echo "Load dump file: pg_dumpall_$${PROJECT_NAME}_`date +"%d.%m.%Y"`.sql.gz" ;\
	  docker exec -u postgres -e PROJECT_NAME=$${PROJECT_NAME} $${PROJECT_NAME}_db_1 \
		bash -c 'zcat /opt/backup/pg_dumpall_$${PROJECT_NAME}_`date +"$d.%m.%Y"`.sql.gz | psql' ; \
	  echo "Load dump complete. Start databases ANALYZE." ; \
	  docker exec -u postgres $${PROJECT_NAME}_db_1 psql -c "ANALYZE" && \
		echo "ANALYZE complete."


# $$PWD используется для того, чтобы текущий каталог был доступен в контейнере по тому же пути
# и относительные тома новых контейнеров могли его использовать
## run docker-compose
dc: docker-compose.yml
	@docker run --rm -t -i \
	  -v /var/run/docker.sock:/var/run/docker.sock \
	  -v $$PWD:$$PWD \
	  -w $$PWD \
	  docker/compose:$(DC_VER) \
	  -p $$PROJECT_NAME \
	  $(CMD)

# ------------------------------------------------------------------------------

# Wait for postgresql container start
docker-wait:
	@echo -n "Checking PG is ready..." ; \
	DCAPE_DB=$${PROJECT_NAME}_db_1 ; \
	until [[ `docker inspect -f "{{.State.Health.Status}}" $$DCAPE_DB` == healthy ]] ; do sleep 1 ; echo -n "." ; done
	@echo "Ok"

# Database import script
# DCAPE_DB_DUMP_DEST must be set in pg container

define IMPORT_SCRIPT
[[ "$$DCAPE_DB_DUMP_DEST" ]] || { echo "DCAPE_DB_DUMP_DEST not set. Exiting" ; exit 1 ; } ; \
DB_NAME="$$1" ; DB_USER="$$2" ; DB_PASS="$$3" ; DB_SOURCE="$$4" ; \
dbsrc=$$DCAPE_DB_DUMP_DEST/$$DB_SOURCE.tgz ; \
if [ -f $$dbsrc ] ; then \
  echo "Dump file $$dbsrc found, restoring database..." ; \
  zcat $$dbsrc | PGPASSWORD=$$DB_PASS pg_restore -h localhost -U $$DB_USER -O -Ft -d $$DB_NAME || exit 1 ; \
else \
  echo "Dump file $$dbsrc not found" ; \
  exit 2 ; \
fi
endef
export IMPORT_SCRIPT

## create database and user
db-create: docker-wait
	@echo "*** $@ ***" \
	&& varname=$(NAME)_DB_PASS && pass=$${!varname} \
	&& varname=$(NAME)_DB_TAG && dbname=$${!varname} \
	&& DCAPE_DB=$${PROJECT_NAME}_db_1 \
	&& docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE USER \"$$dbname\" WITH PASSWORD '$$pass';" \
	&& docker exec -i $$DCAPE_DB psql -U postgres -c "CREATE DATABASE \"$$dbname\" OWNER \"$$dbname\";" || db_exists=1 ; \
	if [[ ! "$$db_exists" ]] && [[ "$(PG_SOURCE_SUFFIX)" ]] ; then \
	    echo "$$IMPORT_SCRIPT" | docker exec -i $$DCAPE_DB bash -s - $$dbname $$dbname $$pass $$dbname$(PG_SOURCE_SUFFIX) \
	    && docker exec -i $$DCAPE_DB psql -U postgres -c "COMMENT ON DATABASE \"$$dbname\" IS 'SOURCE $$dbname$(PG_SOURCE_SUFFIX)';" \
	    || true ; \
	fi

## drop database and user
db-drop:
	@echo "*** $@ ***" \
	&& varname=$(NAME)_DB_TAG && dbname=$${!varname} \
	&& DCAPE_DB=$${PROJECT_NAME}_db_1 \
	&& docker exec -i $$DCAPE_DB psql -U postgres -c "DROP DATABASE \"$$dbname\";" \
	&& docker exec -i $$DCAPE_DB psql -U postgres -c "DROP USER \"$$dbname\";"

psql:
	@DCAPE_DB=$${PROJECT_NAME}_db_1 \
	&& docker exec -it $$DCAPE_DB psql -U postgres

# ------------------------------------------------------------------------------
# .env file store

## get env tag from store, `make env-get TAG=app--config--tag`
env-get:
	@[[ "$(TAG)" ]] || { echo "Error: Tag value required" ; exit 1 ;}
	@echo "Getting env into $(TAG)"
	@docker exec -ti $${PROJECT_NAME}_webhook_1 curl -gs $${ENFIST_URL}/tag_vars?a_code=$(TAG) \
	  | jq -r '.result[0].tag_vars' > $(TAG).env

## set env tag in store, `make env-set TAG=app--config--tag`
env-set:
	@[[ "$(TAG)" ]] || { echo "Error: Tag value required" ; exit 1 ;}
	@echo "Setting $(TAG) from file" \
	&& jq -R -sc ". | {\"a_code\":\"$(TAG)\",\"a_data\":.}" < $(TAG).env | \
	  docker exec -i $${PROJECT_NAME}_webhook_1 curl -gsd @- $${ENFIST_URL}/tag_set > /dev/null

# ------------------------------------------------------------------------------

## delete unused docker images w/o name
clean-noname:
	docker rmi $$(docker images | grep "<none>" | awk "{print \$$3}")
#docker images -q -f dangling=true

## delete docker dangling volumes
clean-volume:
	docker volume rm $$(docker volume ls -qf dangling=true)

# ------------------------------------------------------------------------------

help:
	@grep -A 1 "^##" Makefile | less

##
## Press 'q' for exit
##
