services:
  # ------------------------------------------------------------------------------
  db:
    image: ${PG_IMAGE}:${PG_VER}
    hostname: ${PG_HOSTNAME}
    restart: always
    networks:
      - default
      - intra
    ports:
      - 127.0.0.1:${PG_PORT_LOCAL}:5432
    labels:
      - traefik.enable=false
    environment:
      - POSTGRES_PASSWORD=${PG_DB_PASS}
      - TZ=${TZ}
      - LANG=${PG_ENCODING}
      - DCAPE_DB_DUMP_DEST=/opt/backup
      - POSTGRES_INITDB_ARGS=${PG_INITDB_ARGS}
    volumes:
      - ./${DCAPE_VAR}/db/data:/var/lib/postgresql/data
      - ./${DCAPE_VAR}/db/backup:/opt/backup
      - ./${DCAPE_VAR}/db/conf.d:/opt/conf.d
      - ./${DCAPE_VAR}/db/shared:/opt/shared
      - ./${DCAPE_VAR}/db/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-h", "db"]
      interval: 2s
      timeout: 3s
      retries: 3
    shm_size: ${PG_SHM_SIZE}
    stop_grace_period: 5s
    stop_signal: SIGINT
