  # ------------------------------------------------------------------------------
  traefik:
    image: traefik:${TRAEFIK_VER}
    command:
      --web --docker --docker.watch --docker.exposedbydefault=false --logLevel=DEBUG
      --file --file.directory=/custom --file.watch=true
    restart: always
    labels:
      - "traefik.enable=false"
    ports:
      - "${TRAEFIK_PORT}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/traefik.toml
      - ./var/data/traefik/custom:/custom

