  # ------------------------------------------------------------------------------
  traefik:
    image: traefik:${TRAEFIK_VER}
    restart: always
    ports:
      - "${TRAEFIK_LISTEN}:80"
      - "${TRAEFIK_LISTEN_SSL}:443"
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${DCAPE_HOST}`) && (PathPrefix(`/dashboard/`) || PathPrefix(`/api/`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=narra"
      - "traefik.http.routers.ping.rule=Host(`${DCAPE_HOST}`) && PathPrefix(`/ping`)"
      - "traefik.http.routers.ping.service=ping@internal"
      # HSTS basic settings for shared using (like Nextcloud required and etc.).
      - "traefik.http.middlewares.hsts.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"
      - "traefik.http.middlewares.hsts.headers.forceSTSHeader=true"
    env_file:
      - ${DCAPE_VAR}/traefik/traefik.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./${DCAPE_VAR}/traefik:/etc/traefik
    networks:
      default:
        aliases:
          - ${TRAEFIK_ALIAS}
