services:
  cicd:
    extends:
      file: ${DCAPE_ROOT}/apps/core/docker-compose.tmpl.yml
      service: template-traefik
    image: ${CICD_IMAGE}:${CICD_VER}
    labels:
      - traefik.http.routers.cicd.rule=Host(`${CICD_HOST}`)
      - traefik.http.services.app-cicd.loadbalancer.server.port=8000
    depends_on:
      - cicd-agent
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST=${DCAPE_SCHEME}://${CICD_HOST}
      - WOODPECKER_AGENT_SECRET=${CICD_AGENT_SECRET}
      - WOODPECKER_ADMIN=${CICD_ADMIN}
      - WOODPECKER_GITHUB=${CICD_GITHUB_USED}
      - WOODPECKER_GITHUB_CLIENT=${CICD_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${CICD_GITHUB_SECRET}
      - WOODPECKER_GITEA=${CICD_GITEA_USED}
      - WOODPECKER_GITEA_URL=${AUTH_SERVER}
      - WOODPECKER_GITEA_CLIENT=${CICD_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${CICD_GITEA_SECRET}
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://${CICD_DB_TAG}:${CICD_DB_PASS}@db/${CICD_DB_TAG}?sslmode=disable
      - WOODPECKER_ENVIRONMENT=DCAPE_TAG:${DCAPE_TAG},DCAPE_NET:${DCAPE_NET},DCAPE_ROOT:${DCAPE_ROOT}/${DCAPE_VAR},DCAPE_COMPOSE:${DCAPE_TAG}-compose,DCAPE_SCM:${GITEA_HOST}
#      - WOODPECKER_ESCALATE=docker,plugins/docker,plugins/gcr,plugins/ecr,woodpeckerci/plugin-docker,woodpeckerci/plugin-docker-buildx
      - WOODPECKER_LOG_LEVEL=debug
      #- WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro

  cicd-agent:
    extends:
      file: ${DCAPE_ROOT}/apps/core/docker-compose.tmpl.yml
      service: template
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    volumes:
#      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/docker/certs.d:/etc/docker/certs.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=cicd:9000 # GRPC server
      - WOODPECKER_AGENT_SECRET=${CICD_AGENT_SECRET}
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://${CICD_DB_TAG}:${CICD_DB_PASS}@db/${CICD_DB_TAG}?sslmode=disable
      - WOODPECKER_LOG_LEVEL=debug
      - WOODPECKER_BACKEND_DOCKER_VOLUMES=/etc/ssl/certs:/etc/ssl/certs:ro,/etc/docker/certs.d:/etc/docker/certs.d:ro
      - WOODPECKER_ENVIRONMENT=DCAPE_TAG:${DCAPE_TAG},DCAPE_NET:${DCAPE_NET},DCAPE_ROOT:${DCAPE_ROOT}/${DCAPE_VAR},DCAPE_COMPOSE:${DCAPE_TAG}-compose,DCAPE_SCM:${GITEA_HOST}
