services:
  cicd:
    extends:
      file: ${DCAPE_ROOT}/apps/core/docker-compose.tmpl.yml
      service: template-traefik
    image: ${CICD_IMAGE}:${CICD_VER}
    labels:
      - traefik.http.routers.cicd.rule=Host(`${CICD_HOST}`)
    environment:
      - WOODPECKER_OPEN=false
      - WOODPECKER_HOST=${DCAPE_SCHEME}://${CICD_HOST}
      - WOODPECKER_AGENT_SECRET=${CICD_AGENT_SECRET}
      - WOODPECKER_ADMIN=${CICD_ADMIN_USERS}
      - WOODPECKER_GITHUB=${CICD_GITHUB_USED}
      - WOODPECKER_GITHUB_CLIENT=${CICD_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${CICD_GITHUB_SECRET}
      - WOODPECKER_GITEA=${CICD_GITEA_USED}
      - WOODPECKER_GITEA_URL=${CICD_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${CICD_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${CICD_GITEA_SECRET}
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://${CICD_DB_TAG}:${CICD_DB_PASS}@db/${CICD_DB_TAG}?sslmode=disable
      # TODO:      - DRONE_GIT_ALWAYS_AUTH=true

  cicd-agent:
    extends:
      file: ${DCAPE_ROOT}/apps/core/docker-compose.tmpl.yml
      service: template
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    depends_on:
      - cicd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=cicd:9000 # GRPC server
      - WOODPECKER_AGENT_SECRET=${CICD_AGENT_SECRET}
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_DATABASE_DATASOURCE=postgres://${CICD_DB_TAG}:${CICD_DB_PASS}@db/${CICD_DB_TAG}?sslmode=disable

