services:
  template:
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  template-traefik:
    extends:
      service: template
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
