services:
  # ------------------------------------------------------------------------------
  powerdns:
    image: ghcr.io/dopos/powerdns-alpine:${PDNS_VER}
    restart: always
    ports:
      - "${PDNS_LISTEN}:53"
      - "${PDNS_LISTEN}:53/udp"
    hostname: ${ACME_NS}
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.powerdns.rule=Host(`${PDNS_HOST}`)"
      - "traefik.http.routers.powerdns.middlewares=narra"
      - "traefik.http.services.powerdns.loadbalancer.server.port=8081"
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8081"
      - "prometheus.io/extra-labels=job:powerdns"
    environment:
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_API=yes
      - PDNS_CHROOT=/
      - PDNS_DAEMON=no
      - PDNS_GPGSQL_DBNAME=${PDNS_DB_TAG}
      - PDNS_GPGSQL_HOST=db
      - PDNS_GPGSQL_PASSWORD=${PDNS_DB_PASS}
      - PDNS_GPGSQL_PORT=5432
      - PDNS_GPGSQL_USER=${PDNS_DB_TAG}
      - PDNS_LAUNCH=gpgsql,bind
      - PDNS_MASTER=yes
      - PDNS_SOCKET_DIR=/var/run
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_ALLOW_FROM=0.0.0.0/0
      - PDNS_WEBSERVER_PORT=8081
      - PDNS_WEBSERVER=yes
#      - PDNS_LOG_DNS_QUERIES=yes
#      - PDNS_LOGLEVEL=5


    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/etc/pdns.conf
