  # ------------------------------------------------------------------------------
  powerdns:
    image: ghcr.io/dopos/powerdns-alpine:${PDNS_VER}
    restart: always
    ports:
      - "${PDNS_LISTEN}:53"
      - "${PDNS_LISTEN}:53/udp"
    hostname: ${ACME_NS}
    depends_on:
      db:
        condition: service_healthy
    command:
      --master --daemon=no --chroot=/ --socket-dir=/var/run --launch=gpgsql --api=yes --api-key=${PDNS_API_KEY}
      --webserver --webserver-address=0.0.0.0 --webserver-port=8081 --webserver-allow-from=0.0.0.0/0
      --gpgsql-host=db --gpgsql-dbname=${PDNS_DB_TAG} --gpgsql-user=${PDNS_DB_TAG} --gpgsql-password=${PDNS_DB_PASS}
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.powerdns.rule=Host(`${PDNS_HOST}`)"
      - "traefik.http.routers.powerdns.middlewares=narra"
      - "traefik.http.services.powerdns.loadbalancer.server.port=8081"
    environment:
      - MYSQL_DEFAULT_AUTOCONF=false
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/etc/pdns.conf
